# Generated by Django 5.0.2 on 2024-02-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=4000)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tourist Spot',
                'verbose_name_plural': 'Tourist Spots',
            },
        ),
    ]
