# Generated by Django 5.0.2 on 2024-02-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attractions', '0002_rename_atrraction_attraction'),
        ('comments_reviews', '0002_review_comment_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=4000)),
                ('is_approved', models.BooleanField(default=False)),
                ('attractions', models.ManyToManyField(default='', to='attractions.attraction')),
                ('comment', models.ManyToManyField(blank=True, default='', to='comments_reviews.comment')),
            ],
            options={
                'verbose_name': 'Tourist Spot',
                'verbose_name_plural': 'Tourist Spots',
            },
        ),
    ]
