# Generated by Django 5.0.2 on 2024-02-26 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_reviews', '0001_initial'),
        ('tourist_attractions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='comment',
        ),
        migrations.AddField(
            model_name='touristspot',
            name='comment',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='comments_reviews.comment'),
            preserve_default=False,
        ),
    ]
