# Generated by Django 5.0.2 on 2024-02-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_reviews', '0002_review_comment_review'),
        ('tourist_attractions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='comment',
            field=models.ManyToManyField(default='', to='comments_reviews.comment'),
        ),
    ]
