# Generated by Django 5.0.2 on 2024-02-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_reviews', '0001_initial'),
        ('tourist_attractions', '0002_touristspot_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='Comment',
            field=models.ManyToManyField(default='', to='comments_reviews.comment'),
        ),
    ]
