# Generated by Django 5.0.2 on 2024-02-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_reviews', '0002_comment_tourist_spot'),
        ('tourist_attractions', '0003_alter_touristspot_address_alter_touristspot_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='comment',
        ),
        migrations.AddField(
            model_name='touristspot',
            name='comment',
            field=models.ManyToManyField(blank=True, to='comments_reviews.comment'),
        ),
    ]
