# Generated by Django 5.0.2 on 2024-02-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_attractions', '0005_touristspot_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='tourist-attractions/%Y/%m/'),
        ),
    ]
