# Generated by Django 5.0.2 on 2024-02-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('work_time', models.TextField()),
                ('minimal_age', models.IntegerField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='tourist-attractions/attractions/%Y/%m/')),
            ],
        ),
    ]
