# Generated by Django 5.0.2 on 2024-02-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atrraction',
            new_name='Attraction',
        ),
    ]
