# Generated by Django 5.0.2 on 2024-02-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_rename_atrraction_attraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='tourist-attractions/attractions/%Y/%m/'),
        ),
    ]
