# Generated by Django 5.0.2 on 2024-02-26 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_reviews', '0001_initial'),
        ('tourist_attractions', '0003_alter_touristspot_address_alter_touristspot_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tourist_spot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tourist_attractions', to='tourist_attractions.touristspot'),
            preserve_default=False,
        ),
    ]
